-- ========================================
-- COMPREHENSIVE SCHEMA MIGRATION SCRIPT
-- Supabase Project Migration: Old → New
-- ========================================
-- Run this in SQL Editor of the NEW Supabase project
-- Project URL: https://jkqkywrckwkppfoezyes.supabase.co

-- ========================================
-- 1. ENABLE REQUIRED EXTENSIONS
-- ========================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ========================================
-- 2. CREATE HELPER FUNCTION FOR updated_at
-- ========================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = NOW();
   RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ========================================
-- 3. CREATE MAIN TABLES
-- ========================================

-- 3.1 PROFILES TABLE
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE,
  username TEXT UNIQUE NOT NULL,
  full_name TEXT,
  role TEXT NOT NULL DEFAULT 'viewer' CHECK (role IN ('admin', 'viewer', 'commentator')),
  email TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (id)
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- 3.2 PPA TABLE (Permohonan Perbaikan Alat)
CREATE TABLE IF NOT EXISTS public.ppa (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  tanggal DATE NOT NULL,
  no_ppa VARCHAR(50) NOT NULL UNIQUE,
  nama_alat VARCHAR(255) NOT NULL,
  no_lambung VARCHAR(50) NOT NULL,
  kerusakan TEXT NOT NULL,
  keterangan TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  approved_by VARCHAR(255),
  approved_at TIMESTAMP WITH TIME ZONE
);

ALTER TABLE public.ppa ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_ppa_no_ppa ON public.ppa(no_ppa);
CREATE INDEX IF NOT EXISTS idx_ppa_no_lambung ON public.ppa(no_lambung);
CREATE INDEX IF NOT EXISTS idx_ppa_status ON public.ppa(status);
CREATE INDEX IF NOT EXISTS idx_ppa_tanggal ON public.ppa(tanggal);

-- 3.3 TIMESHEET TABLE
CREATE TABLE IF NOT EXISTS public.timesheet (
    id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    tanggal DATE NOT NULL,
    no_lambung TEXT,
    nama_operator TEXT NOT NULL,
    nama_alat TEXT NOT NULL,
    sesi1_jam_mulai TIME,
    sesi1_jam_selesai TIME,
    sesi2_jam_mulai TIME,
    sesi2_jam_selesai TIME,
    sesi3_jam_mulai TIME,
    sesi3_jam_selesai TIME,
    total_jam NUMERIC NOT NULL DEFAULT 0,
    aktivitas TEXT NOT NULL,
    lokasi TEXT NOT NULL,
    keterangan TEXT,
    bbm NUMERIC,
    oli_40 NUMERIC,
    oli_10 NUMERIC,
    oli_90 NUMERIC,
    created_by UUID REFERENCES auth.users,
    updated_by UUID REFERENCES auth.users,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

ALTER TABLE public.timesheet ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER update_timesheet_updated_at
    BEFORE UPDATE ON public.timesheet
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- 3.4 KEGIATAN_MEKANIK TABLE
CREATE TABLE IF NOT EXISTS public.kegiatan_mekanik (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tanggal DATE NOT NULL,
    no_ppa VARCHAR(50) NOT NULL,
    no_lambung VARCHAR(50) NOT NULL,
    nama_alat VARCHAR(255) NOT NULL,
    nama_mekanik VARCHAR(255) NOT NULL,
    lokasi_pekerjaan TEXT NOT NULL,
    keterangan TEXT,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.kegiatan_mekanik ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER update_kegiatan_mekanik_updated_at
    BEFORE UPDATE ON public.kegiatan_mekanik
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- 3.5 RPA TABLE
CREATE TABLE IF NOT EXISTS public.rpa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rpa_id VARCHAR(50) NOT NULL UNIQUE,
    tanggal DATE NOT NULL,
    item_pekerjaan TEXT NOT NULL,
    lokasi_proyek TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.rpa ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER update_rpa_updated_at
    BEFORE UPDATE ON public.rpa
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- 3.6 RPA_DETAILS TABLE
CREATE TABLE IF NOT EXISTS public.rpa_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rpa_id BIGINT NOT NULL REFERENCES public.rpa(id) ON DELETE CASCADE,
    nama_alat TEXT NOT NULL,
    uraian_pekerjaan TEXT,
    mulai_tanggal DATE,
    selesai_tanggal DATE,
    keterangan TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.rpa_details ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER update_rpa_details_updated_at
    BEFORE UPDATE ON public.rpa_details
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- 3.7 PERBAIKAN TABLE (created if not exists)
CREATE TABLE IF NOT EXISTS public.perbaikan (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    tanggal DATE NOT NULL,
    no_perbaikan VARCHAR(50) NOT NULL UNIQUE,
    nama_alat VARCHAR(255) NOT NULL,
    no_lambung VARCHAR(50) NOT NULL,
    kerusakan TEXT NOT NULL,
    keterangan TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'pending'
);

ALTER TABLE public.perbaikan ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER update_perbaikan_updated_at
    BEFORE UPDATE ON public.perbaikan
    FOR EACH ROW
    EXECUTE FUNCTION update_modified_column();

-- 3.8 ALAT_BERAT TABLE
CREATE TABLE IF NOT EXISTS public.alat_berat (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    nama_alat VARCHAR(255) NOT NULL,
    no_lambung VARCHAR(50) NOT NULL UNIQUE,
    jenis_alat VARCHAR(100),
    tahun_perolehan INTEGER,
    nilai_perolehan NUMERIC,
    lokasi TEXT,
    status VARCHAR(50) DEFAULT 'aktif',
    keterangan TEXT
);

ALTER TABLE public.alat_berat ENABLE ROW LEVEL SECURITY;

-- 3.9 ALAT_PENDUKUNG TABLE
CREATE TABLE IF NOT EXISTS public.alat_pendukung (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    nama_alat VARCHAR(255) NOT NULL,
    no_lambung VARCHAR(50),
    jenis_alat VARCHAR(100),
    tahun_perolehan INTEGER,
    nilai_perolehan NUMERIC,
    lokasi TEXT,
    status VARCHAR(50) DEFAULT 'aktif',
    keterangan TEXT
);

ALTER TABLE public.alat_pendukung ENABLE ROW LEVEL SECURITY;

-- 3.10 BBM_TRANSACTIONS TABLE
CREATE TABLE IF NOT EXISTS public.bbm_transactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    tanggal DATE NOT NULL,
    jenis_bbm VARCHAR(50),
    jumlah NUMERIC NOT NULL,
    satuan VARCHAR(20),
    no_lambung VARCHAR(50),
    nama_alat VARCHAR(255),
    cost NUMERIC,
    keterangan TEXT
);

ALTER TABLE public.bbm_transactions ENABLE ROW LEVEL SECURITY;

-- 3.11 OLI_TRANSACTIONS TABLE
CREATE TABLE IF NOT EXISTS public.oli_transactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    tanggal DATE NOT NULL,
    jenis_oli VARCHAR(50),
    jumlah NUMERIC NOT NULL,
    satuan VARCHAR(20),
    no_lambung VARCHAR(50),
    nama_alat VARCHAR(255),
    cost NUMERIC,
    keterangan TEXT
);

ALTER TABLE public.oli_transactions ENABLE ROW LEVEL SECURITY;

-- 3.12 BBM_STOCKS TABLE
CREATE TABLE IF NOT EXISTS public.bbm_stocks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    jenis_bbm VARCHAR(50) NOT NULL,
    jumlah_stock NUMERIC NOT NULL DEFAULT 0,
    satuan VARCHAR(20),
    harga_satuan NUMERIC,
    keterangan TEXT
);

ALTER TABLE public.bbm_stocks ENABLE ROW LEVEL SECURITY;

-- 3.13 OLI_STOCKS TABLE
CREATE TABLE IF NOT EXISTS public.oli_stocks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    jenis_oli VARCHAR(50) NOT NULL,
    jumlah_stock NUMERIC NOT NULL DEFAULT 0,
    satuan VARCHAR(20),
    harga_satuan NUMERIC,
    keterangan TEXT
);

ALTER TABLE public.oli_stocks ENABLE ROW LEVEL SECURITY;

-- 3.14 SPAREPART TABLE
CREATE TABLE IF NOT EXISTS public.sparepart (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    nama_sparepart VARCHAR(255) NOT NULL,
    deskripsi TEXT,
    satuan VARCHAR(20),
    harga NUMERIC,
    jumlah_stock NUMERIC DEFAULT 0,
    keterangan TEXT
);

ALTER TABLE public.sparepart ENABLE ROW LEVEL SECURITY;

-- 3.15 SEWA_ALAT TABLE
CREATE TABLE IF NOT EXISTS public.sewa_alat (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    tanggal_sewa DATE,
    tanggal_kembali DATE,
    nama_alat VARCHAR(255),
    no_lambung VARCHAR(50),
    penyewa VARCHAR(255),
    biaya_sewa NUMERIC,
    keterangan TEXT
);

ALTER TABLE public.sewa_alat ENABLE ROW LEVEL SECURITY;

-- 3.16 SEWA_ALAT_EKSTERNAL TABLE
CREATE TABLE IF NOT EXISTS public.sewa_alat_eksternal (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    tanggal_sewa DATE,
    tanggal_kembali DATE,
    nama_alat VARCHAR(255),
    vendor VARCHAR(255),
    biaya_sewa NUMERIC,
    keterangan TEXT
);

ALTER TABLE public.sewa_alat_eksternal ENABLE ROW LEVEL SECURITY;

-- ========================================
-- 4. CREATE FUNCTIONS FOR AUTH & PROFILES
-- ========================================

DROP FUNCTION IF EXISTS public.handle_new_user() CASCADE;

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, username, full_name, role, email)
  VALUES (
    NEW.id,
    NEW.raw_user_meta_data->>'username',
    NEW.raw_user_meta_data->>'full_name',
    COALESCE(NEW.raw_user_meta_data->>'role', 'viewer')::TEXT,
    NEW.email
  )
  ON CONFLICT (id) DO UPDATE SET
    username = EXCLUDED.username,
    full_name = EXCLUDED.full_name,
    role = EXCLUDED.role,
    email = EXCLUDED.email,
    updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Helper functions
CREATE OR REPLACE FUNCTION public.get_user_role(p_user_id UUID)
RETURNS text AS $$
  SELECT role FROM public.profiles WHERE id = p_user_id;
$$ LANGUAGE sql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.is_admin(p_user_id UUID DEFAULT NULL)
RETURNS boolean AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = COALESCE(p_user_id, auth.uid()) AND role = 'admin'
  );
$$ LANGUAGE sql SECURITY DEFINER;

-- ========================================
-- 5. CREATE RLS POLICIES
-- ========================================

-- 5.1 PROFILES POLICIES
DROP POLICY IF EXISTS "Allow public signups" ON public.profiles;
DROP POLICY IF EXISTS "Users can view own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
DROP POLICY IF EXISTS "Allow email lookup by username" ON public.profiles;
DROP POLICY IF EXISTS "Admins can view all profiles" ON public.profiles;

CREATE POLICY "Allow public signups"
ON public.profiles
FOR INSERT
WITH CHECK (true);

CREATE POLICY "Users can view own profile"
ON public.profiles
FOR SELECT
USING (auth.uid() = id OR public.is_admin());

CREATE POLICY "Users can update own profile"
ON public.profiles
FOR UPDATE
USING (auth.uid() = id OR public.is_admin())
WITH CHECK (auth.uid() = id OR public.is_admin());

CREATE POLICY "Allow email lookup by username"
ON public.profiles
FOR SELECT
USING (true);

-- 5.2 PPA POLICIES
DROP POLICY IF EXISTS "Enable read access for all users" ON public.ppa;
DROP POLICY IF EXISTS "Enable insert for authenticated users" ON public.ppa;
DROP POLICY IF EXISTS "Enable update for authenticated users" ON public.ppa;
DROP POLICY IF EXISTS "Allow public insert to ppa" ON public.ppa;
DROP POLICY IF EXISTS "Allow public update to ppa" ON public.ppa;
DROP POLICY IF EXISTS "Allow public delete to ppa" ON public.ppa;

CREATE POLICY "Allow public read" ON public.ppa FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.ppa FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.ppa FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON public.ppa FOR DELETE USING (true);

-- 5.3 TIMESHEET POLICIES
DROP POLICY IF EXISTS "Users can view all timesheets" ON public.timesheet;
DROP POLICY IF EXISTS "Users can insert timesheets" ON public.timesheet;
DROP POLICY IF EXISTS "Users can update timesheets" ON public.timesheet;
DROP POLICY IF EXISTS "Users can delete timesheets" ON public.timesheet;
DROP POLICY IF EXISTS "Allow public insert to timesheet" ON public.timesheet;
DROP POLICY IF EXISTS "Allow public update to timesheet" ON public.timesheet;
DROP POLICY IF EXISTS "Allow public delete to timesheet" ON public.timesheet;

CREATE POLICY "Allow public read" ON public.timesheet FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.timesheet FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.timesheet FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON public.timesheet FOR DELETE USING (true);

-- 5.4 KEGIATAN_MEKANIK POLICIES
DROP POLICY IF EXISTS "Enable read access for all users" ON public.kegiatan_mekanik;
DROP POLICY IF EXISTS "Enable insert for authenticated users" ON public.kegiatan_mekanik;
DROP POLICY IF EXISTS "Enable update for authenticated users" ON public.kegiatan_mekanik;
DROP POLICY IF EXISTS "Enable all access for admin" ON public.kegiatan_mekanik;
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON public.kegiatan_mekanik;

CREATE POLICY "Allow public read" ON public.kegiatan_mekanik FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.kegiatan_mekanik FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.kegiatan_mekanik FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON public.kegiatan_mekanik FOR DELETE USING (true);

-- 5.5 RPA POLICIES
DROP POLICY IF EXISTS "Enable read access for all users" ON public.rpa;
DROP POLICY IF EXISTS "Enable insert for authenticated users" ON public.rpa;
DROP POLICY IF EXISTS "Enable update for authenticated users" ON public.rpa;

CREATE POLICY "Allow public read" ON public.rpa FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.rpa FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.rpa FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON public.rpa FOR DELETE USING (true);

-- 5.6 RPA_DETAILS POLICIES
DROP POLICY IF EXISTS "Enable read access for all users" ON public.rpa_details;
DROP POLICY IF EXISTS "Enable insert for authenticated users" ON public.rpa_details;
DROP POLICY IF EXISTS "Enable update for authenticated users" ON public.rpa_details;

CREATE POLICY "Allow public read" ON public.rpa_details FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.rpa_details FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.rpa_details FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON public.rpa_details FOR DELETE USING (true);

-- 5.7 PERBAIKAN POLICIES
DROP POLICY IF EXISTS "Enable read access for all users" ON public.perbaikan;
DROP POLICY IF EXISTS "Enable insert for authenticated users" ON public.perbaikan;
DROP POLICY IF EXISTS "Enable update for authenticated users" ON public.perbaikan;
DROP POLICY IF EXISTS "Enable delete for authenticated users" ON public.perbaikan;
DROP POLICY IF EXISTS "Allow public insert to perbaikan" ON public.perbaikan;
DROP POLICY IF EXISTS "Allow public update to perbaikan" ON public.perbaikan;
DROP POLICY IF EXISTS "Allow public delete to perbaikan" ON public.perbaikan;

CREATE POLICY "Allow public read" ON public.perbaikan FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.perbaikan FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.perbaikan FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON public.perbaikan FOR DELETE USING (true);

-- 5.8 ALAT_BERAT POLICIES
DROP POLICY IF EXISTS "Allow public insert to alat_berat" ON public.alat_berat;
DROP POLICY IF EXISTS "Allow public update to alat_berat" ON public.alat_berat;
DROP POLICY IF EXISTS "Allow public delete to alat_berat" ON public.alat_berat;

CREATE POLICY "Allow public read" ON public.alat_berat FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.alat_berat FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.alat_berat FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON public.alat_berat FOR DELETE USING (true);

-- 5.9 ALAT_PENDUKUNG POLICIES
DROP POLICY IF EXISTS "Allow public insert to alat_pendukung" ON public.alat_pendukung;
DROP POLICY IF EXISTS "Allow public update to alat_pendukung" ON public.alat_pendukung;
DROP POLICY IF EXISTS "Allow public delete to alat_pendukung" ON public.alat_pendukung;

CREATE POLICY "Allow public read" ON public.alat_pendukung FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.alat_pendukung FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.alat_pendukung FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON public.alat_pendukung FOR DELETE USING (true);

-- 5.10 BBM_TRANSACTIONS POLICIES
DROP POLICY IF EXISTS "Allow public insert to bbm_transactions" ON public.bbm_transactions;
DROP POLICY IF EXISTS "Allow public update to bbm_transactions" ON public.bbm_transactions;
DROP POLICY IF EXISTS "Allow public delete to bbm_transactions" ON public.bbm_transactions;

CREATE POLICY "Allow public read" ON public.bbm_transactions FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.bbm_transactions FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.bbm_transactions FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON public.bbm_transactions FOR DELETE USING (true);

-- 5.11 OLI_TRANSACTIONS POLICIES
DROP POLICY IF EXISTS "Allow public insert to oli_transactions" ON public.oli_transactions;
DROP POLICY IF EXISTS "Allow public update to oli_transactions" ON public.oli_transactions;
DROP POLICY IF EXISTS "Allow public delete to oli_transactions" ON public.oli_transactions;

CREATE POLICY "Allow public read" ON public.oli_transactions FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.oli_transactions FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.oli_transactions FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON public.oli_transactions FOR DELETE USING (true);

-- 5.12 BBM_STOCKS POLICIES
DROP POLICY IF EXISTS "Allow public insert to bbm_stocks" ON public.bbm_stocks;
DROP POLICY IF EXISTS "Allow public update to bbm_stocks" ON public.bbm_stocks;
DROP POLICY IF EXISTS "Allow public delete to bbm_stocks" ON public.bbm_stocks;

CREATE POLICY "Allow public read" ON public.bbm_stocks FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.bbm_stocks FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.bbm_stocks FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON public.bbm_stocks FOR DELETE USING (true);

-- 5.13 OLI_STOCKS POLICIES
DROP POLICY IF EXISTS "Allow public insert to oli_stocks" ON public.oli_stocks;
DROP POLICY IF EXISTS "Allow public update to oli_stocks" ON public.oli_stocks;
DROP POLICY IF EXISTS "Allow public delete to oli_stocks" ON public.oli_stocks;

CREATE POLICY "Allow public read" ON public.oli_stocks FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.oli_stocks FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.oli_stocks FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON public.oli_stocks FOR DELETE USING (true);

-- 5.14 SPAREPART POLICIES
CREATE POLICY "Allow public read" ON public.sparepart FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.sparepart FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.sparepart FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON public.sparepart FOR DELETE USING (true);

-- 5.15 SEWA_ALAT POLICIES
CREATE POLICY "Allow public read" ON public.sewa_alat FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.sewa_alat FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.sewa_alat FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON public.sewa_alat FOR DELETE USING (true);

-- 5.16 SEWA_ALAT_EKSTERNAL POLICIES
CREATE POLICY "Allow public read" ON public.sewa_alat_eksternal FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.sewa_alat_eksternal FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.sewa_alat_eksternal FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON public.sewa_alat_eksternal FOR DELETE USING (true);

-- ========================================
-- 6. GRANT NECESSARY PERMISSIONS
-- ========================================
GRANT SELECT ON public.profiles TO anon, authenticated;
GRANT UPDATE ON public.profiles TO authenticated;

GRANT ALL ON public.ppa TO authenticated, anon;
GRANT ALL ON public.timesheet TO authenticated, anon;
GRANT ALL ON public.kegiatan_mekanik TO authenticated, anon;
GRANT ALL ON public.rpa TO authenticated, anon;
GRANT ALL ON public.rpa_details TO authenticated, anon;
GRANT ALL ON public.perbaikan TO authenticated, anon;
GRANT ALL ON public.alat_berat TO authenticated, anon;
GRANT ALL ON public.alat_pendukung TO authenticated, anon;
GRANT ALL ON public.bbm_transactions TO authenticated, anon;
GRANT ALL ON public.oli_transactions TO authenticated, anon;
GRANT ALL ON public.bbm_stocks TO authenticated, anon;
GRANT ALL ON public.oli_stocks TO authenticated, anon;
GRANT ALL ON public.sparepart TO authenticated, anon;
GRANT ALL ON public.sewa_alat TO authenticated, anon;
GRANT ALL ON public.sewa_alat_eksternal TO authenticated, anon;

-- ========================================
-- SUCCESS: Schema migration completed!
-- ========================================
-- Run the following to verify:
-- SELECT table_name FROM information_schema.tables
-- WHERE table_schema = 'public' ORDER BY table_name;
