-- Create kegiatan_mekanik table
CREATE TABLE IF NOT EXISTS public.kegiatan_mekanik (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tanggal DATE NOT NULL,
    no_ppa VARCHAR(50) NOT NULL,
    no_lambung VARCHAR(50) NOT NULL,
    nama_alat VARCHAR(255) NOT NULL,
    nama_mekanik VARCHAR(255) NOT NULL,
    lokasi_pekerjaan TEXT NOT NULL,
    keterangan TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create RLS policies for kegiatan_mekanik table
ALTER TABLE public.kegiatan_mekanik ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" 
    ON public.kegiatan_mekanik 
    FOR SELECT 
    USING (true);

CREATE POLICY "Enable insert for authenticated users" 
    ON public.kegiatan_mekanik 
    FOR INSERT 
    TO authenticated 
    WITH CHECK (true);

CREATE POLICY "Enable update for authenticated users" 
    ON public.kegiatan_mekanik 
    FOR UPDATE 
    TO authenticated 
    USING (true);

-- Create rpa table
CREATE TABLE IF NOT EXISTS public.rpa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rpa_id VARCHAR(50) NOT NULL UNIQUE,
    tanggal DATE NOT NULL,
    item_pekerjaan TEXT NOT NULL,
    lokasi_proyek TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create rpa_details table
CREATE TABLE IF NOT EXISTS public.rpa_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rpa_id BIGINT NOT NULL REFERENCES public.rpa(id) ON DELETE CASCADE,
    nama_alat TEXT NOT NULL,
    uraian_pekerjaan TEXT,
    mulai_tanggal DATE,
    selesai_tanggal DATE,
    keterangan TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create RLS policies for rpa table
ALTER TABLE public.rpa ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" 
    ON public.rpa 
    FOR SELECT 
    USING (true);

CREATE POLICY "Enable insert for authenticated users" 
    ON public.rpa 
    FOR INSERT 
    TO authenticated 
    WITH CHECK (true);

CREATE POLICY "Enable update for authenticated users" 
    ON public.rpa 
    FOR UPDATE 
    TO authenticated 
    USING (true);

-- Create RLS policies for rpa_details table
ALTER TABLE public.rpa_details ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" 
    ON public.rpa_details 
    FOR SELECT 
    USING (true);

CREATE POLICY "Enable insert for authenticated users" 
    ON public.rpa_details 
    FOR INSERT 
    TO authenticated 
    WITH CHECK (true);

CREATE POLICY "Enable update for authenticated users" 
    ON public.rpa_details 
    FOR UPDATE 
    TO authenticated 
    USING (true);

-- Create function to update updated_at column
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = NOW();
   RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create triggers for updated_at
CREATE TRIGGER update_kegiatan_mekanik_updated_at
BEFORE UPDATE ON public.kegiatan_mekanik
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_rpa_updated_at
BEFORE UPDATE ON public.rpa
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_rpa_details_updated_at
BEFORE UPDATE ON public.rpa_details
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();
